# Generated by Django 3.2.3 on 2021-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
    ]
